### ISSUE TITLE
Accuracy comparison with v1.1

### ISSUE THREAD

**Issue by gudovskiy** [miaow1988/SqueezeNet_v1.2#1]
@miaow1988 your results with the removed squeeze layer ReLUs seem surprising. Did you try to compare accuracy numbers for model with and without squeeze layer ReLUs using exactly the same setup you have?

**Comment by miaow1988** [comment]
Yes, I did. Here are different ImageNet top-1 accuracy using same configuration.
1. SqueezeNet V1.1 (with squeeze layer ReLUs): Acc.=58.0%.
2. SqueezeNet V1.2 (without squeeze layer ReLUs): Acc.=61.0%.

MobileNet V2 did similar things compared with MobileNet V1.

**Comment by ujsyehao** [comment]
Your work performs well! @miaow1988
